### PR TITLE
Add Union Pay support

### PR DESCRIPTION
**Pull request by khomsovon**

### CODE REVIEW

**Comment by orazz** [comment]
Please provide tested screenshots.
p.s. stripe doesn't support UnionPay

**Comment by khomsovon** [comment]
Please see the screenshot for the UnionPay Card.

Stripe started supporting UnionPay back in June, although they didn't make a big deal of announcing it. See link: https://stripe.com/blog/payments-updates-june-2018

alt text
alt text

alt text

**Comment by orazz** [comment]
Ok, Thanks. reopen pr.

**Comment by khomsovon** [comment]
Yes thank you.

**Pull request closed without merging**
