### PR TITLE
Rename CreditCardForum.h to CreditCardForm.h

### PR DESCRIPTION
**Pull request by ayushgoel**
Fixed typo.

### CODE REVIEW

**Comment by ayushgoel** [comment]
I hope it is not intentional, another file is named so. https://github.com/orazz/CreditCardForm-iOS/blob/master/CreditCardForm/Classes/CreditCardForumView.swift

**Comment by ayushgoel** [comment]
@orazz no reason for close?

**Comment by orazz** [comment]
@ayushgoel [Fixed typo and released 0.0.6](https://github.com/orazz/CreditCardForm-iOS/commit/3bb86c7017c6a6cc08baf2048ce8c2fe0762c94a)

**Comment by ayushgoel** [comment]
🆒 👍

**Pull request closed without merging**
